version: "3"

services:
  link_api:
    build:
      context: ./api/link
      dockerfile: Dockerfile
    volumes:
      - ./api/link:/link_api
    environment:
      DEV: 1
      MYSQL_DATABASE: area
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:9000
    restart: always

  start_service_api:
    build:
      context: ./api/link
      dockerfile: Dockerfile
    volumes:
      - ./api/link:/link_api
    environment:
      DEV: 1
      MYSQL_DATABASE: area
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    links:
      - db
    depends_on:
      - db
    command: "sh ./start_service_api.sh"
    restart: always

  intra_api:
    build:
      context: ./api/intra
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
    restart: always

  github_api:
    build:
      context: ./api/github
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
      PORT: 9000
    restart: always

  currency_api:
    build:
      context: ./api/currency
      dockerfile: Dockerfile
    environment:
      DEV_ENV: "TRUE"
    restart: always

  weather_api:
   build:
     context: ./api/weather
     dockerfile: Dockerfile
   environment:
     DEV_ENV: "TRUE"
   restart: always

  email_backup_api:
   build: 
     context: ./api/email-back-up
     dockerfile: Dockerfile
   environment:
     DEV_ENV: "TRUE"
   restart: always

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: area
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /sessions

  front:
    environment:
      ANDROID_HOME: /usr/local/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    build:
      context: ./area_front
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./statics:/statics
    ports:
      - 8081:80

  front_apk:
    environment:
      ANDROID_HOME: /usr/local/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    build:
      context: ./area_front
      dockerfile: Dockerfile_apk
    volumes:
      - ./statics:/statics
