# Generated by Django 3.0.2 on 2020-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_applet', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=12)),
                ('enable', models.BooleanField()),
                ('user_id', models.CharField(max_length=255)),
                ('action_service', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('action_logo', models.CharField(max_length=100)),
                ('reaction_service', models.CharField(max_length=50)),
                ('reaction', models.CharField(max_length=50)),
                ('reaction_logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParamApplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.BooleanField()),
                ('value', models.CharField(max_length=100)),
                ('applet_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
