# Generated by Django 3.0.2 on 2020-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Microsoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='applet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='applet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applet',
            name='name',
        ),
        migrations.AddField(
            model_name='paramapplet',
            name='side',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applet',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applet',
            name='id_applet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paramapplet',
            name='applet_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paramapplet',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
