# Generated by Django 3.0.2 on 2020-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('action_name', models.CharField(max_length=50)),
                ('reaction_name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('value_to_compare', models.CharField(max_length=255)),
            ],
        ),
    ]
