# Generated by Django 3.0.2 on 2020-02-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='refresh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intra',
            name='refresh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='microsoft',
            name='refresh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slack',
            name='refresh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='github',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='intra',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='microsoft',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slack',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
