# Generated by Django 3.0.2 on 2020-02-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0004_auto_20200216_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Value',
        ),
    ]
