# Generated by Django 3.0.3 on 2020-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0005_delete_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='applet',
            name='data',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
