# Generated by Django 3.0.3 on 2020-02-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0006_applet_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Microsoft',
            new_name='Google',
        ),
    ]
