# Generated by Django 3.0.3 on 2020-02-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0009_notif_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
