# Generated by Django 3.0.3 on 2020-02-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_api', '0011_auto_20200225_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activate', models.BooleanField(default=False)),
            ],
        ),
    ]
