from link_api.models import Title, Description, Color
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = 'Fill database with default data'

    def handle(self, *args, **options):
        if Title.objects.all().count() == 32 and Description.objects.all().count() == 32 and Color.objects.all().count():
            return

        Title.objects.all().delete()
        Description.objects.all().delete()
        Color.objects.all().delete()

        Title(value="Be warned on Slack in the event of a commit", name="0").save()
        Title(value="Be notified by email in the event of a commit", name="1").save()
        Title(value="Receive a notification in the event of a commit", name="2").save()
        Title(value="Be warned on Slack in case of temperature increase", name="3").save()
        Title(value="Receive an email if the temperature rises", name="4").save()
        Title(value="Receive notification when temperature rises", name="5").save()
        Title(value="Be warned on Slack if the temperature drops", name="6").save()
        Title(value="Receive an email if the temperature drops", name="7").save()
        Title(value="Receive a notification when the temperature drops", name="8").save()
        Title(value="Get notified on Slack if an email is received", name="9").save()
        Title(value="Notifier la reception d'une email sur email", name="10").save()
        Title(value="Receive a notification if you receive an email", name="11").save()
        Title(value="Get notified on Slack if there is a new note", name="12").save()
        Title(value="Receive an email if there is a new note", name="13").save()
        Title(value="Receive notification if there is a new note", name="14").save()
        Title(value="Be notified on Slack if there is a new credit", name="15").save()
        Title(value="Receive an email if there is a new credit", name="16").save()
        Title(value="Receive a notification if there is a new credit", name="17").save()
        Title(value="Be warned on Slack if the GPA drops", name="18").save()
        Title(value="Receive an email if the GPA drops", name="19").save()
        Title(value="Receive notification if GPA drops", name="20").save()
        Title(value="Be warned on Slack if the GPA increases", name="21").save()
        Title(value="Receive an email if the GPA increases", name="22").save()
        Title(value="Receive a notification if the GPA increases", name="23").save()
        Title(value="Be warned on Slack if the price of a currency drops", name="24").save()
        Title(value="Receive an email if the price of a currency drops", name="25").save()
        Title(value="Receive a notification if the price of a currency drops", name="26").save()
        Title(value="Be warned on Slack if the price of a currency increases", name="27").save()
        Title(value="Receive an email if the price of a currency increases", name="28").save()
        Title(value="Receive a notification if the price of a currency increases", name="29").save()
        Title(value="Get notified on Slack if there is a Slack notification", name="30").save()
        Title(value="Receive an email if there is a Slack notification", name="31").save()
        Title(value="Receive notification if there is a Slack notification", name="32").save()

        Description(value="Envoyer un méssage sur slack lors de l'arrivé d'un nouveau commit sur un repository à spécifier", name="0").save()
        Description(value="Envoyer un email sur slack lors de l'arrivé d'un nouveau commit sur un repository à spécifier", name="1").save()
        Description(value="Envoyer une notification sur slack lors de l'arrivé d'un nouveau commit sur un repository à spécifier", name="2").save()
        Description(value="Envoyer un méssage sur slack lors que la température dépasse un seuil donné", name="3").save()
        Description(value="Envoyer un email via google mail lors que la température dépasse un seuil donné", name="4").save()
        Description(value="Envoyer une notification lors que la température dépasse un seuil donné", name="5").save()
        Description(value="Envoyer un méssage sur slack lors que la température descent en dessous d'un seuil donné", name="6").save()
        Description(value="Envoyer un email via google mail lors que la température descent en dessous d'un seuil donné", name="7").save()
        Description(value="Envoyer une notification lors que la température descent en dessous d'un seuil donné", name="8").save()
        Description(value="Envoyer un méssage sur slack lors de la reception d'un email sur gmail", name="9").save()
        Description(value="Envoyer un email via google mail lors de la reception d'un email sur gmail", name="10").save()
        Description(value="Envoyer une notification lors de la reception d'un email sur gmail", name="11").save()
        Description(value="Envoyer un méssage sur slack lors qu'une note venant de l'intra epitech est en dessous d'un seuil donné", name="12").save()
        Description(value="Envoyer un email via google mail lors qu'une note venant de l'intra epitech est en dessous d'un seuil donné", name="13").save()
        Description(value="Envoyer une notification lors qu'une note venant de l'intra epitech est en dessous d'un seuil donné", name="14").save()
        Description(value="Envoyer un méssage sur slack lors que un crédit de l'intra epitech est au dessus d'un seuil donné", name="15").save()
        Description(value="Envoyer un email via google mail lors que un crédit de l'intra epitech est au dessus d'un seuil donné", name="16").save()
        Description(value="Envoyer une notification lors que un crédit de l'intra epitech est au dessus d'un seuil donné", name="17").save()
        Description(value="Envoyer un méssage sur slack lors que le GPA de l'intra epitech en dessous d'un seuil donné", name="18").save()
        Description(value="Envoyer un email via google mail lors que le GPA de l'intra epitech en dessous d'un seuil donné", name="19").save()
        Description(value="Envoyer une notification lors que le GPA de l'intra epitech en dessous d'un seuil donné", name="20").save()
        Description(value="Envoyer un méssage sur slack lors que le GPA de l'intra epitech au dessus d'un seuil donné", name="21").save()
        Description(value="Envoyer un email via google mail lors que le GPA de l'intra epitech au dessus d'un seuil donné", name="22").save()
        Description(value="Envoyer une notification lors que le GPA de l'intra epitech au dessus d'un seuil donné", name="23").save()
        Description(value="Envoyer un méssage sur slack lors qu'une monnaie passe en dessous d'un seuil donné en fonction de l'euro", name="24").save()
        Description(value="Envoyer un email via google mail lors qu'une monnaie passe en dessous d'un seuil donné en fonction de l'euro", name="25").save()
        Description(value="Envoyer une notification lors qu'une monnaie passe en dessous d'un seuil donné en fonction de l'euro", name="26").save()
        Description(value="Envoyer un méssage sur slack lors qu'une monnaie passe au dessus d'un seuil donné en fonction de l'euro", name="27").save()
        Description(value="Envoyer un email via google mail lors qu'une monnaie passe au dessus d'un seuil donné en fonction de l'euro", name="28").save()
        Description(value="Envoyer une notification lors qu'une monnaie passe au dessus d'un seuil donné en fonction de l'euro", name="29").save()
        Description(value="Envoyer un méssage sur slack lors de la reception d'une nouvelle notification slack", name="30").save()
        Description(value="Envoyer un email via google mail lors de la reception d'une nouvelle notification slack", name="31").save()
        Description(value="Envoyer une notification lors de la reception d'une nouvelle notification slack", name="32").save()

        Color(value="0xff0366d6", name="0").save()
        Color(value="0xffffd33d", name="1").save()
        Color(value="0xffd73a49", name="2").save()
        Color(value="0xffe3f4fe", name="3").save()
        Color(value="0xff19c3fb", name="4").save()
        Color(value="0xffe3f4fe", name="5").save()
        Color(value="0xff1d71f2", name="6").save()
        Color(value="0xff1c9cf6", name="7").save()
        Color(value="0xfffffae0", name="8").save()
        Color(value="0xffb23121", name="9").save()
        Color(value="0xffc6c6c6", name="10").save()
        Color(value="0xffd44638", name="11").save()
        Color(value="0xffBFE4FF", name="12").save()
        Color(value="0xffD3D4D4", name="13").save()
        Color(value="0xffEAF6FF", name="14").save()
        Color(value="0xffBFE4FF", name="15").save()
        Color(value="0xff009FFD", name="16").save()
        Color(value="0xffD3D4D4", name="17").save()
        Color(value="0xffEAF6FF", name="18").save()
        Color(value="0xffD3D4D4", name="19").save()
        Color(value="0xffBFE4FF", name="20").save()
        Color(value="0xff009FFD", name="21").save()
        Color(value="0xffEAF6FF", name="22").save()
        Color(value="0xffBFE4FF", name="23").save()
        Color(value="0xffffffff", name="24").save()
        Color(value="0xff4d4d4d", name="25").save()
        Color(value="0xff329239", name="26").save()
        Color(value="0xff0d579b", name="27").save()
        Color(value="0xff4d4d4d", name="28").save()
        Color(value="0xffffffff", name="29").save()
        Color(value="0xfff2606a", name="30").save()
        Color(value="0xff779846", name="31").save()
        Color(value="0xffffd57e", name="32").save()
